export const USER_ACTION_TYPES = {
	SET_USERS: 'SET_USERS',
	SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
	SET_CURRENT_USERS: 'SET_CURRENT_USERS',
	SET_META: 'SET_META',
	SET_SEARCH_TERM: 'SET_SEARCH_TERM',
};
